### ISSUE TITLE
Xrender libs missing

### ISSUE THREAD

**Issue by zeruth** [lakka-switch/Lakka-LibreELEC#20]
While not really an issue as you could build this in yourself, It feels like a lot of work for literally nothing. Ran into this after downloading 32bit Java:

libXrender.so.1: cannot open shared object file: No such file or directory

I'd like to request that those are included in future builds please. Java is incredibly useful for a use-case such as this.

And looking upstream it seems they have libXrender just not libXrender1

**Comment by natinusala** [comment]
`Java is incredibly useful for a use-case such as this.` such as what ? What are you trying to do here ? 

`And looking upstream it seems they have libXrender just not libXrender1` it's the same thing actually

**Comment by zeruth** [comment]
Well I intend to play a java game - Old School Runescape. 

Honestly I thought that may be the case. but we have it in our project:
https://github.com/lakka-switch/Lakka-LibreELEC/tree/master/packages/x11/lib/libXrender

so I don't understand why it can't find it.

**Comment by zeruth** [comment]
could it have to do with this? 

PKG_CONFIGURE_OPTS_TARGET="--enable-static **--disable-shared** --enable-malloc0returnsnull"

**Comment by natinusala** [comment]
Yes, it's only built as static library. I can add it for the next nightly if you want

**Comment by zeruth** [comment]
I mean if it's a small patch that'd be awesome. I know you got a lot to work out on here but having java means a lot to me and this is the best linux impl i've seen by far. I'll try to figure out building it so I can do more stuff with it

**Comment by natinusala** [comment]
Try this : https://transfer.sh/aNEk9/Lakka-Switch.arm-2.2-devel-20181219143439-r28359-gdcbb80ff5.tar.gz

**Comment by zeruth** [comment]
Yeah that did the trick for that error. I guess there are other libs that require that patch. the next one is libxtst. I couldn't get my build to go through. What environment do you use to build. and how do i use the toolchain you mentioned instead of the one ubuntu installs?

Probably most x11 libs will need to be shared

**Comment by natinusala** [comment]
Don't you have a way to check the list of all needed libs ? So that I add them all at once instead of one by one, it will take ages (and it's a PITA to upload)

**Comment by zeruth** [comment]
I don't think so. it terminates the program as soon as it hits the first exception. That's why I am trying to build it. but build failed in 64bit Ubuntu 18 and 32bit Ubuntu 14...

**Comment by natinusala** [comment]
Open the Java classes in jd-gui and search for all occurences of natives library loading ?

**Comment by zeruth** [comment]
Well the source for the project is on github I could probably just look there. :facepalm: I'll update in a bit

**Comment by zeruth** [comment]
Actually looking already, the program itself isn't requesting those libraries. Its java awt. I'm not going to keep bugging you with this though. I'll try to figure out building and work on it in my spare time. I appreciate the help though

**Comment by natinusala** [comment]
This should have all the x11 libs as shared libs : https://transfer.sh/2Pcl5/Lakka-Switch.arm-2.2-devel-20181219215045-r28359-gdcbb80ff5.tar.gz

**Comment by zeruth** [comment]
Thank you so much! I'll try it as soon as I get home, been out running holiday errands. Really though you've gone well out of your way to do something that you didnt even need. I appreciate you

**Comment by zeruth** [comment]
![screen](https://user-images.githubusercontent.com/2943260/50257734-97688f80-03ca-11e9-9950-d9ef159759e2.jpg)

🎆 Success! 🎆  

GPU support seems to be malfunctioning but that's generally a problem with linux atm as it's a new feature in the client.

CPU overclocking makes it a playable experience until that is fixed. 

But wow! Thanks a lot man!!

**Comment by natinusala** [comment]
You're welcome! GPU support works fine in Linux but it's limited to OpenGL so if your game uses DirectX then it won't work.

Also, you should quit RetroArch using `systemctl stop retroarch` or add `retroarch=0` to the boot command line
