### ISSUE TITLE
XLIB_RANDR

### ISSUE THREAD

**Issue by zeruth** [lakka-switch/Lakka-LibreELEC#21]
I've tried building this from nearly every DIST and docker but it fails every time.

![randr](https://user-images.githubusercontent.com/2943260/50491184-12d7cb80-09df-11e9-820d-c826466c4fc6.png)

xrandr clearly exists but this build script is borked.

**Comment by natinusala** [comment]
No it's not borked. You need to add `libxrandr` to the target dependencies of whatever package you're trying to build.

As for your screenshot, it doesn't show anything. The build script can't find the _target_ dependency, and you're showing that the _host_ PC has it.

**Comment by zeruth** [comment]
I literally just ran the build script - changed nothing, why on earth would i have to change dependencies on a fixed build? its mesa btw

EDIT: yeah adding xrandr to PKG_DEPENDS_TARGET in mesa package.mk fixed the problem.

**Comment by natinusala** [comment]
Why would mesa need xrandr though, did you edit it ? If not, I need to push a fix

**Comment by zeruth** [comment]
No I didnt edit it. With a completely clean git pull, that edit was necessary to get past mesa. It should be pushed

**Comment by natinusala** [comment]
Ok thanks, I will update it to get past meat ;)

**Comment by zeruth** [comment]
@natinusala hahahaha yeah I seen that. Use fasthub so autocorrect wants to get me lol
