### ISSUE TITLE
FSCK black screen at boot

### ISSUE THREAD

**Issue by zeruth** [lakka-switch/Lakka-LibreELEC#22]
So I don't know if this is because of low end sd cards or what. but for me (even before I was building) When I boot Lakka - sometimes it will just stay at a black screen indefinitely (roughly 75& of the time). When removing the sd card and putting it back into pc, there are a ton of remnant FSCK files. 

Pretty obviously getting stuck during/after FSCK but I can't tell.

My first thought was to add the fastboot option to bootloader but that didn't work, now i'm trying to patch out fstab to default all drives to no fsck at creation.

Any other ideas?

EDIT: It actually appears like fstab isnt generated at all, so what could I do to prevent fsck from running rampantly?

**Comment by natinusala** [comment]
This is a known issue. We already have a fix, visit us on Discord to try it early.

**Comment by 0xCCD** [comment]
Does this fix already find his way into the nightly build ? I had the same issue

**Comment by natinusala** [comment]
This issue has no reason to exist anymore since the change to L4T kernel
