### ISSUE TITLE
L4T - error when connecting to wifi

### ISSUE THREAD

**Issue by plaidman** [lakka-switch/Lakka-LibreELEC#36]
immediately after entering your password, you will get an error popup along the lines of: `Error /net/connman/service/wifi_7cbb8a87c69b_574f5721353737342d3547_managed_psk: Method "Connect" with signature "" on interface "net.connman.Service" doesn't exist`
The connection eventually goes through just fine, the menu indicates that wifi is connected properly, and I am able to connect to the switch.

**Comment by plaidman** [comment]
upgrading to the latest version of connman (1.37) does not fix the issue.

**Comment by natinusala** [comment]
What happens if you issue the command `agent on` in connmanctl and then try to connect again?

**Comment by plaidman** [comment]
```
connmanctl> agent on
Agent registered
```

Then when I try to choose a wifi AP, I get the same message and in my console I get:

```
Agent unregistered by ConnMan
connmanctl> connmanctl>
```

**Comment by plaidman** [comment]
patch has been PRd to upstream

**Comment by natinusala** [comment]
One retroarch update away from the fix
