### ISSUE TITLE
Controller problem

### ISSUE THREAD

**Issue by TheRealSlimShady420** [lakka-switch/Lakka-LibreELEC#55]
I just downloaded it from your locker TV site and like whenever I try GameCube N64 or Dreamcast games the games think the left analog stick on the left joycon is being pushed up.
I don't have a gif to problem because my controller works 100% fine in Horizon
Again I just downloaded lakka an amusing whatever latest was on your site

**Comment by TheRealSlimShady420** [comment]
Lakka TV site***

**Comment by plaidman** [comment]
This is likely not a lakka issue. Stick drift is more pronounced in lakka, so despite not seeing it in horizon, that doesn't mean it's not there. Try with a brand new joycon.

**Comment by HarleyPato** [comment]
Well.

For GC try to press X , Y and + button at the same time. It should recalibrate itself.

**Comment by natinusala** [comment]
Not if the decalibration comes from the actual Joy-Con

**Comment by MrHomebrew** [comment]
Go in to the input setting and add just a slight bit of deadzone. Will stop the drifting 😉

**Comment by TheRealSlimShady420** [comment]
Omfg

**Comment by TheRealSlimShady420** [comment]
0
It's not a joycon issue

**Comment by TheRealSlimShady420** [comment]
Didn't I mention it works fine in Horizon?

**Comment by TheRealSlimShady420** [comment]
Because the joycon seems to be"drifting " when I start the games either 64 Dreamcast or GameCube but when I start a game in Horizon let's say smash Brothers or Mario Kart it works 100% fine

**Comment by natinusala** [comment]
Horizon has better calibration handling to compensate drifting. Lakka doesn't. You were given solutions, please try them or close the issue

**Comment by TheRealSlimShady420** [comment]
So if you guys are thinking it's a controller issue you guys must be lying to yourselves

**Comment by TheRealSlimShady420** [comment]
I should also mention stick drifting does not happen when they use my joycons as a mouse for l4t

**Comment by TheRealSlimShady420** [comment]
It's a lakka issue

**Comment by TheRealSlimShady420** [comment]
Just open my box of New Joy cons and same thing so you guys thinking it's a stick drifting issue it's not... god you guys are stupid

**Comment by TheRealSlimShady420** [comment]
Closest an issue that's still an issue

**Comment by TheRealSlimShady420** [comment]
No it's being left open.

**Comment by TheRealSlimShady420** [comment]
you guys are fucking stupid I'm trying to ask for help and you guys are trying to dodge the bug and say it's not an issue? I just prove to you guys that I use brand new controllers and it does the same shit

**Comment by TheRealSlimShady420** [comment]
Fucking learn to read

**Comment by natinusala** [comment]
You were given solutions and you ignored them. Stop spamming or I will ban you from this repository

**Comment by p-sam** [comment]
learn to manners, or just deal with your drifting, and us drifting away

**Comment by TheRealSlimShady420** [comment]
Donna Summers repository? I'll make more accounts and piss you off even more like a little bitch you are. I ask for help solutions what about fixing drifting issues which I DO NOT HAVE!!!

**Comment by natinusala** [comment]
To the trash you go
