### ISSUE TITLE
Ubuntu L4T booting instead of Lakka

### ISSUE THREAD

**Issue by lordfriky** [lakka-switch/Lakka-LibreELEC#62]
I copied the Ubuntu L4T ext4 partition to the same SD card where I have Lakka and now I cannot boot it, every time I select Lakka in Hekate it boots Ubuntu instead

**Comment by natinusala** [comment]
Update Ubuntu

**Comment by lordfriky** [comment]
Thank you so much, I didn't know the boot folder was still there lol
